Inotify
ml4ai/tomcat-faceAnalyzer pull request #7
Opened 2022-05-03 00:44 UTC by Vatsav14

- Option to use images in NFS shared drive from ffmpeg

2022-05-03 17:44 UTC, adarshp requested changes
There is a lot of duplicated code between NFSSensor.cpp and WebcamSensor.cpp. Please refactor to reduce the amount of code duplication. You can do this by having a base class that both WebcamSensor and NFSSensor inherit from, some free functions that both classes use, or a combination of both these strategies.

2022-05-13 10:04 UTC, Vatsav14 reviewed
Completed the requested changes!

2022-06-05 15:54 UTC, adarshp approved these changes

2022-06-05 15:54 UTC, adarshp approved these changes

2022-06-05 15:55 UTC, merged